
namespace DistrictPassportLibrary.Models
{
    public interface IPassportModel
    {
        //DateTime Date { get; set; }
        //int Divorces { get; set; }
        //int Id { get; set; }
        //int Marriages { get; set; }
        //int Population { get; set; }
        //int Quarter { get; set; }
        //int YearInfo { get; set; }

        int Id { get; set; }
        int YearInfo { get; set; }
        int QuarterInfo { get; set; }
        DateTime EntryDate { get; set; }
        int DistrPopulation { get; set; }
        int Marriages { get; set; }
        int Divorces { get; set; }
        int LargeFamilies { get; set; }
        int ParentsDeprivedPr { get; set; }
        int ParentsLimitedPr { get; set; }
        int ParentsRestoredPr { get; set; }
        int SopParents { get; set; }
        int SopChildren { get; set; }
        int AlimonyDebtors { get; set; }
        int AlimonySumm { get; set; }
        int OnPrevRecords { get; set; }
        int ChildPopulation { get; set; }
        int Newborns { get; set; }
        int NewbornsDeaths { get; set; }
        int ChildDeathsExternals { get; set; }
        int CdMva { get; set; }
        int CdDrowned { get; set; }
        int CdFire { get; set; }
        int ChildSuicides { get; set; }
        int ChildSuicideAttempts { get; set; }
        int SopMinors { get; set; }
        int DisabledChildren { get; set; }
        int Preschoolers { get; set; }
        int PreschoolEducationals { get; set; }
        int PreEdUnlicensed { get; set; }
        int ChildlinePreschool { get; set; }
        int Schools { get; set; }
        int SchUnlicensed { get; set; }
        int Graders1to4 { get; set; }
        int Graders5to11 { get; set; }
        int SelfEducated { get; set; }
        int SedAttached { get; set; }
        int Colleges { get; set; }
        int ClgsUnlicensed { get; set; }
        int CollegeStudents { get; set; }
        int ClgsForeigners { get; set; }
        int Universities { get; set; }
        int UnvUnlicensed { get; set; }
        int Students { get; set; }
        int StForeigners { get; set; }
        int Dormitories { get; set; }
        int Orphans { get; set; }
        int FosterFamilies { get; set; }
        int FosterKids { get; set; }
        int FosterKidsReturned { get; set; }
        int FkretByFamilies { get; set; }
        int Orphanages { get; set; }
        int LivingInOrphanages { get; set; }
        int RaisedByGuardians { get; set; }
        int Adopted { get; set; }
        int HomelessAt18 { get; set; }
        int HousingAt18 { get; set; }
        int CrimesByMinors { get; set; }
        int CrimesAgainstMinors { get; set; }
        int ConvictedMinors { get; set; }
        int AdmoffensesByMinors { get; set; }
        int PdnRegistered { get; set; }
        int RegisteredDrugs { get; set; }
        int RegisteredAlcohol { get; set; }

        string DistrPopulationC { get; set; }
        string MarriagesC { get; set; }
        string DivorcesC { get; set; }
        string LargeFamiliesC { get; set; }
        string ParentsDeprivedPrC { get; set; }
        string ParentsLimitedPrC { get; set; }
        string ParentsRestoredPrC { get; set; }
        string SopParentsC { get; set; }
        string SopChildrenC { get; set; }
        string AlimonyDebtorsC { get; set; }
        string AlimonySummC { get; set; }
        string OnPrevRecordsC { get; set; }
        string ChildPopulationC { get; set; }
        string NewbornsC { get; set; }
        string NewbornsDeathsC { get; set; }
        string ChildDeathsExternalsC { get; set; }
        string CdMvaC { get; set; }
        string CdDrownedC { get; set; }
        string CdFireC { get; set; }
        string ChildSuicidesC { get; set; }
        string ChildSuicideAttemptsC { get; set; }
        string SopMinorsC { get; set; }
        string DisabledChildrenC { get; set; }
        string PreschoolersC { get; set; }
        string PreschoolEducationalsC { get; set; }
        string PreEdUnlicensedC { get; set; }
        string ChildlinePreschoolC { get; set; }
        string SchoolsC { get; set; }
        string SchUnlicensedC { get; set; }
        string Graders1to4C { get; set; }
        string Graders5to11C { get; set; }
        string SelfEducatedC { get; set; }
        string SedAttachedC { get; set; }
        string CollegesC { get; set; }
        string ClgsUnlicensedC { get; set; }
        string CollegeStudentsC { get; set; }
        string ClgsForeignersC { get; set; }
        string UniversitiesC { get; set; }
        string UnvUnlicensedC { get; set; }
        string StudentsC { get; set; }
        string StForeignersC { get; set; }
        string DormitoriesC { get; set; }
        string OrphansC { get; set; }
        string FosterFamiliesC { get; set; }
        string FosterKidsC { get; set; }
        string FosterKidsReturnedC { get; set; }
        string FkretByFamiliesC { get; set; }
        string OrphanagesC { get; set; }
        string LivingInOrphanagesC { get; set; }
        string RaisedByGuardiansC { get; set; }
        string AdoptedC { get; set; }
        string HomelessAt18C { get; set; }
        string HousingAt18C { get; set; }
        string CrimesByMinorsC { get; set; }
        string CrimesAgainstMinorsC { get; set; }
        string ConvictedMinorsC { get; set; }
        string AdmoffensesByMinorsC { get; set; }
        string PdnRegisteredC { get; set; }
        string RegisteredDrugsC { get; set; }
        string RegisteredAlcoholC { get; set; }
        string Comments { get; set; }

    }
}